import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightblue", padding: "1rem"}}>
            <nav>
              <div>
                      <h2>JANINE</h2>
                  <div>
                      {/* <div>
                          <button type="button">HOME</button>
                          <button type="button">
                            <span>Toggle Dropdown</span>
                          </button>
      
                          <div>
                              <a class="dropdown-item" href="webDev.html" target="_blank">WEB DEVELOPMENT</a>
                              <a class="dropdown-item" href="dataAd.html" target="_blank">DATA ADMINISTRATION</a>
                              <hr class="dropdown-divider">
                              <a class="dropdown-item" href="#about">ABOUT</a>
                              <a class="dropdown-item" href="#contact">CONTACTS</a>
                          </div>
                      </div> */}
      
                  </div>
              </div>
          </nav>
        </header>

        {children}

        <footer style={{backgroundColor: "ghostwhite", padding: "1rem"}}>
          Footer
        </footer>
      </body>
    </html>
  );
}
